### ISSUE TITLE
pod install fails

### ISSUE THREAD

**Issue by mihahribar** [backchannel/BackchannelSDK-iOS#3]
Added `pod 'Backchannel' to my Podfile, ran`pod install` and it reports an error.

```
Resolving dependencies of `Podfile`
[!] Unable to satisfy the following requirements:

- `Backchannel` required by `Podfile`

Specs satisfying the `Backchannel` dependency were found, but they required a higher minimum deployment target.
```

Installing any other pod works as expected. The only problematic pod is Backchannel.

**Comment by khanlou** [comment]
Backchannel requires iOS 8.0. Is your project iOS 7?

**Comment by mihahribar** [comment]
Ah, yeah. Didn't see that requirement. Sorry.
