### ISSUE TITLE
Missing Terms of Use on Backchannel.io

### ISSUE THREAD

**Issue by paulstringer** [backchannel/BackchannelSDK-iOS#6]
Hey guys, great potential service and I'm hoping to recommend it to client I'm working with. 

They've asked me a good question which is what are the terms of use. As Screenshots of apps will be uploaded and hosted by Backchannel.io they're interested to know these given this would be for an App in Beta which may have sensitive details which it would be good to know regards ownership of those images and posts.

Ideally terms of use would be available at Backchannel.io which I could point them at so legal could take a look and decide if it's something they can go with publicly.

**Comment by khanlou** [comment]
We're working with the lawyers on a sensible ToS and privacy policy. I hope to have something good this week, and I'll keep you posted. Github Issues is totally fine by us, but if you have any questions that you want to ask privately, feel free to contact us at support@backchannel.io or sales@backchannel.io.

**Comment by paulstringer** [comment]
Thanks for the update, I'll direct future non code related issues to those addresses.  Thanks for the response here though, very helpful.

**Comment by khanlou** [comment]
@paulstringer You can find the terms of use here http://www.backchannel.io/terms-of-use and the privacy policy here http://www.backchannel.io/privacy-policy. Let me know if you have any questions!
